In [1]:
import os
os.chdir('..')


In [2]:
import sopy as sp
import numpy as np 

2025-05-09 09:34:04.205650: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-05-09 09:34:04.215578: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1746801244.228007    9556 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1746801244.231609    9556 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-05-09 09:34:04.243523: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instr

In [3]:

##sample functions on this lattice in 2D
lattices = 2*[np.linspace(-10,10,100)]
wavenumbers = [0.,0.]
phis        = [0.,0.]

##2D gaussian at (2,6) with sigmas (1,1), and polynominal 0,0
u = sp.vector().gaussian(a = 1,positions = [2,6],sigmas = [1,1],ls = [0,0], lattices = lattices, wavenumbers = wavenumbers , phis = phis)

##2D gaussian at (0.1,-0.6) with sigmas (1,1), and polynominal 0,0
k = sp.vector().gaussian(a = 1,positions = [0.1,-0.6],sigmas = [1,1],ls = [0,0], lattices = lattices, wavenumbers = wavenumbers , phis = phis)
##2D gaussian at (-1,-2) with sigmas (1,1), and polynominal 1,1
k = k.gaussian(a = 2,positions = [-1,-2],sigmas = [1,1],ls = [1,1], lattices = lattices, wavenumbers = wavenumbers , phis = phis)

##2D gaussian at (-2,-5) with sigmas (1,1), and polynominal 1,0
v = k.copy().gaussian(a = 2,positions = [-2,-5],sigmas = [1,1],ls = [1,0], lattices = lattices, wavenumbers = wavenumbers , phis = phis)


##linear dependence factor...
alpha = 0

##take v and remove k from it, and decompose into vector u ; outputing to vector q
q = u.learn(v-k,  alpha = alpha, iterate = 1)

2025-05-09 09:34:11.279826: E external/local_xla/xla/stream_executor/cuda/cuda_driver.cc:152] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected


In [4]:
##distance from q to v-k
(q).dist(v-k), len(q), len(v), len(k), len(v-k)

(<tf.Tensor: shape=(), dtype=float64, numpy=0.0>, 1, 3, 2, 1)

In [5]:
##superior decompositional algorithm to start from scratch to decompose v to partition -canon ranks-
[ v.fibonacci( partition = partition, iterate = 10, total_iterate = 10).dist(v) for partition in range(1,len(v))]

[<tf.Tensor: shape=(), dtype=float64, numpy=1.6799587148811832>,
 <tf.Tensor: shape=(), dtype=float64, numpy=0.5376085108908699>]

In [6]:
##common decompositional algorithm to start from scratch to decompose v to partition -canon ranks-
[ v.decompose( partition = partition, iterate = 10).dist(v) for partition in range(1,len(v))]

[<tf.Tensor: shape=(), dtype=float64, numpy=1.6801365771223775>,
 <tf.Tensor: shape=(), dtype=float64, numpy=0.5969469992196542>]

In [7]:
##LIKE DMRG SWEEP, translate into inner product space
#coupled to a superior decomposition algorithm
bv = v.boost()
[ v.boost().fibonacci(  partition = partition, iterate = 10 ,alpha = 1e-2).unboost().dist(v) for partition in range(1,len(v))]

[<tf.Tensor: shape=(), dtype=float64, numpy=1.6800341619188237>,
 <tf.Tensor: shape=(), dtype=float64, numpy=0.5408418179227552>]