In [1]:
from os import chdir
chdir ('..')
import sopy as sp

2025-04-17 05:58:58.833065: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-04-17 05:58:58.918786: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1744887538.955688    3411 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1744887538.966504    3411 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-04-17 05:58:59.049402: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instr

In [2]:
import numpy as np 

In [3]:
l = [np.linspace(-10,10,100)]
u = sp.vector().gaussian(a = 1,positions = [2,6],sigmas = [1,1],ls = [0,0], lattices = 2*l)
k = sp.vector().gaussian(a = 1,positions = [0.1,-0.6],sigmas = [1,1],ls = [0,0], lattices = 2*l).gaussian(a = 2,positions = [-1,-2],sigmas = [1,1],ls = [1,1], lattices = 2*l)
v = k.copy().gaussian(a = 2,positions = [-2,-5],sigmas = [1,1],ls = [1,0], lattices = 2*l)
alpha = 0
q = u.learn(v-k,  alpha = alpha, iterate = 1)

2025-04-17 05:59:07.784266: E external/local_xla/xla/stream_executor/cuda/cuda_driver.cc:152] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected


In [4]:
(q).dist(v-k)

<tf.Tensor: shape=(), dtype=float64, numpy=0.0>

In [5]:
[ v.fibonacci( partition = partition, iterate = 10, total_iterate = 10).dist(v) for partition in range(1,len(v))]

[<tf.Tensor: shape=(), dtype=float64, numpy=1.806797834236357>,
 <tf.Tensor: shape=(), dtype=float64, numpy=0.48544657999725715>]

In [6]:
[ v.decompose( partition = partition, iterate = 10).dist(v) for partition in range(1,len(v))]

[<tf.Tensor: shape=(), dtype=float64, numpy=1.8069392508595157>,
 <tf.Tensor: shape=(), dtype=float64, numpy=0.5255490607060604>]

In [12]:
bv = v.boost()
[ v.boost().fibonacci(  partition = partition, iterate = 10 ,alpha = 1e-2).unboost().dist(v) for partition in range(1,len(v))]

[<tf.Tensor: shape=(), dtype=float64, numpy=1.80686424608695>,
 <tf.Tensor: shape=(), dtype=float64, numpy=0.488519216041906>]